# Generated by Django 2.1.4 on 2019-01-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='website',
        ),
    ]
