# Generated by Django 2.1.4 on 2019-01-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_remove_startup_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='founded_date',
        ),
    ]
